### ISSUE TITLE
Bug with Permission Interceptor

### ISSUE THREAD

**Issue by ottovw** [kittgen/kittgen-nestjs#51]
TypeError: Cannot read property 'name' of undefined
    at TransformOperationExecutor.transform (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/class-transformer/TransformOperationExecutor.js:211:184)
    at ClassTransformer.classToPlain (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/class-transformer/ClassTransformer.js:9:25)
    at Object.classToPlain (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/class-transformer/index.js:21:29)
    at PermissionInterceptor.transformToPlain (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:40:32)
    at PermissionInterceptor.serialize (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:36:20)
    at MapSubscriber.project (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/@kittgen/nestjs-authorization/dist/nestjs-authorization.cjs.development.js:451:138)
    at MapSubscriber._next (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /mnt/c/Users/ottovw/dev/confidens/api-main/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by edgarmueller** [comment]
@ottovw hey, do you have a reproduction case for this one?

**Comment by edgarmueller** [comment]
Closing as not reproducable.
